name: Auto approve

on:
  pull_request_review:

jobs:
  log_things:
     runs-on: ubuntu-latest
     steps:
       - run: echo "User login is ${{ toJson(github.event.review.user.login) }}"
       - run: echo "User login is ${{ toJson(github.event.review.body) }}"

  check_eligible:
    if: github.event.review.user.login == 'levg34' && github.event.review.body == '🆗'
    runs-on: ubuntu-latest
    steps:
      - name: check eligible
        if: contains(github.event.comment.body, '/:ok:')
        run: echo "Eligible"

  auto-approve:
    needs: check_eligible
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'levg34'
    steps:
      - uses: hmarr/auto-approve-action@v3
