name: Auto approve

on:
  pull_request_review:

jobs:
  auto_approve:
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        if: github.event.review.user.login == 'levg34' && github.event.pull_request.user.login == 'levg34' && contains(github.event.review.body, '🆗')
        uses: hmarr/auto-approve-action@v3
