name: Auto approve

on:
  pull_request_review:
  push:

jobs:
  log_things:
     runs-on: ubuntu-latest
     steps:
       - run: echo github.event.comment.user.login
  check_eligible:
    if: github.event.comment.user.login == 'levg34'
    runs-on: ubuntu-latest
    steps:
      - name: check eligible
        if: contains(github.event.comment.body, '/:ok:')
        run: echo "Eligible"

  auto-approve:
    needs: check_eligible
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'levg34'
    steps:
      - uses: hmarr/auto-approve-action@v3
