name: E2E Tests

# Only trigger, when the Node.js Package workflow succeeded
on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows: ["Node.js Package"]
    types:
      - completed

jobs:
  test:
    # Only run if the Node.js Package workflow succeeded
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        module: [commonjs, ecmascript, ts-node, umd]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install and start ${{ matrix.module }}
        if: matrix.module != 'umd' # skip umd job
        working-directory: ./e2e/${{ matrix.module }}
        run: |
          npm install
          npm list typescript-nedb-orm --depth=0
          npm start
      - name: Report results
        if: always()
        run: |
          printf "Directory\tStatus\n" > e2e.out
          for MODULE in $ { { join (matrix.module, ' ') }}; do
            STATUS=$ (curl -s -H "Authorization: token $ { { secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$ { { github.repository }}/actions/runs/$ { { github.run_id }}/jobs | jq '.jobs[] | select (.name == "Install and start $MODULE") | .conclusion')
            if [ "$STATUS" == "\"success\"" ]; then
              printf "$MODULE\tOK\n" >> e2e.out
            elif [ "$STATUS" == "null" ]; then
              printf "$MODULE\tskipped\n" >> e2e.out
            else
              printf "$MODULE\tKO\n" >> e2e.out
            fi
          done
          cat e2e.out

