name: E2E Tests

# Only trigger, when the Node.js Package workflow succeeded
on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows: ["Node.js Package"]
    types:
      - completed

jobs:
  test:
    # Only run if the Node.js Package workflow succeeded
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        module: [commonjs, ecmascript, ts-node, umd]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install and start ${{ matrix.module }}
        if: matrix.module != 'umd' # skip umd job
        working-directory: ./e2e/${{ matrix.module }}
        run: |
          npm install
          npm list typescript-nedb-orm --depth=0
          npm start
